version: '2'
services:
    ewalletservice-app:
        image: ewalletservice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ewalletservice-mysql:3306/ewalletservice?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://ewalletservice-elasticsearch:9200
        ports:
            - 8080:8080
    ewalletservice-mysql:
        extends:
            file: mysql.yml
            service: ewalletservice-mysql
    ewalletservice-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ewalletservice-elasticsearch
